image: node:lts

cache:
    paths:
        - node_modules/

before_script:
    - npm install
    - cat $NPM_CREDENTIAL > ~/.npmrc

stages:
    - deploy

Release on NPM:
    stage: deploy
    environment:
        name: production
    script:
        - npm publish --access public
    only:
        - tags
